### PR TITLE
Updating Meteor's stylus to 0.54.5

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by stubailo** [comment]
Whoa, do we actually use a fork? Is this to support the new import syntax from 1.2?

**Comment by mitar** [comment]
No, this is just to upgrade it. I was debugging some other issues and saw that it is very old.

I am planing to add [autoprefixer-stylus](https://www.npmjs.com/package/autoprefixer-stylus) to my version of stylus package. Would that be something Meteor would be interested in having? I can make a pull request. The issue is that nib is very outdated about that. (I am mostly using nib to get prefixes.)

It is like two lines of code change to get autoprefixer in.

**Comment by mitar** [comment]
Also, is there a list of browsers officially supported by Meteor? So that I could configure autoprefixer to add prefixes for all those browsers.

**Comment by stubailo** [comment]
I think a reasonable choice is to have IE 8+ and all evergreen browsers.

About the fork thing, I'm just curious since I don't remember why this repository, `meteor/stylus` exists, in addition to the `stylus` package in `meteor/meteor`. Seems like this is a fork of "real" stylus, which I think exists so that we can override some import logic.

**Comment by stubailo** [comment]
Also, would anybody be surprised to see `autoprefixer-stylus` included? Is it easy to disable it for people who don't want it?

**Comment by mitar** [comment]
Exactly. Meteor `stylus` package is using this fork to change importing. [See diff](https://github.com/stylus/stylus/compare/master...meteor:master). I update the master and kept Meteor changes. This is this pull request.

**Comment by mitar** [comment]
> Also, would anybody be surprised to see autoprefixer-stylus included? Is it easy to disable it for people who don't want it?

Yes, I am using `addFiles` file options. You can disable it through that. By default I would specify all browsers Meteor supports ([looking here](http://meteorpedia.com/read/Supported_Browsers)). But you can change defaults if you want.

**Comment by stubailo** [comment]
OK, I'll leave it to @tmeasday to merge, publish, and make sure the new version is included in a future Meteor release. Thanks for answering all of my questions!

**Comment by mitar** [comment]
> Also, would anybody be surprised to see autoprefixer-stylus included?

It might be a surprise, but it is similar to moving to babel. So maybe we could even make it a big feature. And use autoprefixer for normal css as well. (There is a package [for it](https://github.com/sebakerckhof/meteor-minifiers-autoprefix), but it works only in production.)

**Comment by stubailo** [comment]
Hmmm, automatic autoprefixer support would definitely be a cool "meteor-ish" feature, that would align with my understanding of a batteries-included build tool. (in the same vein as babel by default in Meteor 1.2+)

Is there some people we can get feedback from about that? I don't know what the best way is to do it - opening a forum thread, or posting an issue on meteor/meteor? I don't know if there are some hidden problems that would make that a dealbreaker for people. There probably aren't but could be good as a sanity check.

**Comment by mitar** [comment]
I can make a pull request for Stylus and we can see what people think about that. I can also open a forum post.

**Comment by stubailo** [comment]
> I can make a pull request for Stylus

I would suggest it's best to discuss these things on an issue first, rather than in the form of a PR, since a PR indicates an up-front investment. I understand it's very little code, but I think it's worth following the process.

**Comment by mitar** [comment]
I [opened a forum post](https://forums.meteor.com/t/what-people-think-about-using-autoprefixer-by-default-in-meteor/28648).

> I would suggest it's best to discuss these things on an issue first, rather than in the form of a PR, since a PR indicates an up-front investment. I understand it's very little code, but I think it's worth following the process.

I already have it because I need it for myself. :-)

**Comment by tmeasday** [comment]
Thanks @mitar. Can you send a PR to bump the package dependency and I'll release it?

Would you like to be a maintainer of stylus?

**Comment by mitar** [comment]
> Can you send a PR to bump the package dependency and I'll release it?

OK.

> Would you like to be a maintainer of stylus?

I would say, I am OK with commit bit, but I would not put myself officially into an (only one) maintainer position. :-)

**Comment by tmeasday** [comment]
> I would say, I am OK with commit bit, but I would not put myself officially into an (only one) maintainer position. :-)

Yeah I guess I just mean publishing rights for the package and commit bits on this repo. We could potentially move the core meteor package here too

**Comment by mitar** [comment]
I know. I just want to be clear to not raise too high expectations. (It seems to me that people think I will do magic with Blaze, and I was mostly just raising my hand that I can help a bit, not that I will lead the whole thing now. But, ah, this is what one gets for not being able to be quiet.)

**Comment by mitar** [comment]
It might be useful to see if core package could be sent upstream.

**Comment by tmeasday** [comment]
Yeah I definitely think a PR to stylus could make sense, if you have the time to do it. Otherwise we can just keep doing this I guess.

**Pull request merged**
